services:
  - type: web
    name: fentsports-backend
    env: node
    buildCommand: npm install
    startCommand: node server.cjs
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://fentsports.win